### Create a new Central 1
POST localhost:8080/api/central
Content-Type: application/json

{
  "name": "Central Bruno",
  "email": "bruno.y.l.imai@gmail.com",
  "password": "central0000",
    "cellphone": "11999999999",
  "cnpj": "12348678902234"
}

### Create a new Central 2
POST localhost:8080/api/central
Content-Type: application/json

{
  "name": "aaaaaa",
  "email": "batata1@gmail.com",
  "password": "12345678",
  "cellphone": "11999999999",
  "cnpj": "12312678902234"
}

### Login como Central 1
POST localhost:8080/api/central/login
Content-Type: application/json

{
  "email": "bruno.y.l.imai@gmail.com",
  "password": "central0000"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.central.id)
%}


### Listar Todos os clientes da central
GET localhost:8080/api/central/client
Authorization: Bearer {{token}}

### Cadastra um Cliente
POST localhost:8080/api/central/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Bruno",
    "cpf": "12345678902",
    "address": "R. do Semeador, 702 - Cidade Industrial de Curitiba, Curitiba - PR, 81270-050",
    "complement": null,
    "cellphone": "11999999999",
    "email": "bruno.k.l.imai@gmail.com"
}

### Esqueci a senha central 1
POST localhost:8080/api/central/login/sendToken?email=bruno.y.l.imai@gmail.com

### Validar o token central 1
POST localhost:8080/api/central/login/validateToken?email=bruno.y.l.imai@gmail.com&code=320cce

### Alterar a senha
POST localhost:8080/api/central/login/resetPassword
Content-Type: application/json

{
    "password": "NovaSenha1234",
    "token": "320cce"
}

### Criar novo Worker
POST localhost:8080/api/central/worker
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cleber",
    "email": "cle@gmail.com",
    "password": "12345678",
    "cellphone": "11999999999",
    "cpf": "12455678901",
    "address": "Rua dos bobos, n 0"
}

### Criar novo Worker
POST localhost:8080/api/central/worker
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Jose",
  "email": "jose@gmail.com",
  "password": "12345678",
  "cellphone": "11999999999",
  "cpf": "12255678902",
  "address": "Rua dos bobos, n 0"
}

### Criar novo Worker
POST localhost:8080/api/central/worker
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Joses",
  "email": "joses@gmail.com",
  "password": "12345678",
  "cellphone": "11999999999",
  "cpf": "12265678902",
  "address": "Rua dos bobos, n 0"
}

### Lista todos os Workers
GET localhost:8080/api/central/worker
Authorization: Bearer {{token}}

### Lista um Worker
GET localhost:8080/api/central/worker/52
Authorization: Bearer {{token}}

### Atualiza um Worker
PUT localhost:8080/api/central/worker/52
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cleiton",
    "email": "teste@gmail.com",
    "password": "12345678",
    "cellphone": "11999999999",
    "cpf": "12345678901",
    "address": "Rua dos bobos, n 0"
}

### Deleta um Worker
DELETE localhost:8080/api/central/worker/2
Authorization: Bearer {{token}}


### Lista o usuário 2
GET localhost:8080/api/central/client/
Authorization: Bearer {{token}}

### lista todos os usuários
GET localhost:8080/api/central/client
Authorization: Bearer {{token}}

### Cria categoria
POST localhost:8080/api/central/category
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Eletricista"
}

### Lista todas as categorias
GET localhost:8080/api/central/category
Authorization: Bearer {{token}}

### Atualiza categoria
PUT localhost:8080/api/central/category/1?name=Ar-Condicionado
Authorization: Bearer {{token}}

### Deleta categoria
DELETE localhost:8080/api/central/category/1
Authorization: Bearer {{token}}

### Cadastra serviço 1
POST localhost:8080/api/central/assistance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Geladeira",
  "name": "Concerto",
  "address": "Av. São Sebastião, 340 - Centro, Quatro Barras - PR, 81270-050, Brazil",
  "cpf": "123.456.789-02",
  "period": "Manha",
  "workersIds": [],
  "categoriesId": [1]
}

### Cadastra serviço 2
POST localhost:8080/api/central/assistance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Concerto churrasqueira",
  "name": "Concerto",
  "address": "Av. Com. Franco, 4680 - Uberaba, Curitiba - PR, 81530-440, Brazil",
  "cpf": "12345678901",
  "period": "Manha",
  "workersIds": [1],
  "categoriesId": [1]
}

### Cadastra serviço 3
POST localhost:8080/api/central/assistance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Concerto ar condicionado",
  "name": "Concerto",
  "address": "Av. Getúlio Vargas, 573 - Centro, Piraquara - PR, 83301-010, Brazil",
  "cpf": "12345678901",
  "period": "Manha",
  "workersIds": [1]
}
### Lista todos os serviços
GET localhost:8080/api/central/assistance
Authorization: Bearer {{token}}


### deleta servico 1
DELETE localhost:8080/api/central/assistance/52
Authorization: Bearer {{token}}

### Cria budget Central
POST localhost:8080/api/central/budget
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "budget 4",
  "description": "Concerto maquina de lavar",
  "assistanceId": 1,
  "responsibleWorkersIds": [6],
  "clientId": 1,
  "totalPrice": 9999.0
}


### Atualiza Orcamento
PUT localhost:8080/api/central/budget
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Relatorio novo",
  "description": "Concerto maquina de lavar",
  "assistanceId": 1,
  "responsibleWorkersIds": [1],
  "clientId": 1,
  "totalPrice": 200.00
}

### busca orcamento

GET localhost:8080/api/central/budget/11
Authorization: Bearer {{token}}

### Lista todos os orcamentos
GET localhost:8080/api/central/budget
Authorization: Bearer {{token}}


### Cria relatorio Central
POST localhost:8080/api/central/report
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "orcamento final",
  "description": "Concerto maquina de lavar",
  "assistanceId": 1,
  "responsibleWorkersIds": [1],
  "clientId": 1,
  "totalPrice": 100.00,
  "paymentType": "CREDITO",
  "machinePartExchange": true,
  "delayed": false
}

### Atualiza relatório
PUT localhost:8080/api/central/report
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Relatorio novo",
  "description": "Concerto maquina de lavar",
  "assistanceId": 1,
  "responsibleWorkersIds": [1],
  "clientId": 1,
  "totalPrice": 200.00,
  "paymentType": "CREDITO",
  "machinePartExchange": true,
  "delayed": true
}

### busca relatório

GET localhost:8080/api/central/report/1
Authorization: Bearer {{token}}

### Lista todos os relatórios
GET localhost:8080/api/central/report
Authorization: Bearer {{token}}

### deletar relatorio
DELETE localhost:8080/api/central/report/10
Authorization: Bearer {{token}}

### Lista notificacoes
GET localhost:8080/api/central/notification
Authorization: Bearer {{token}}

### Lista notificacoes nao lidas
GET localhost:8080/api/central/notification/unread
Authorization: Bearer {{token}}

### Busca notificacao
GET localhost:8080/api/central/notification/1
Authorization: Bearer {{token}}

### Deleta orcamento
DELETE localhost:8080/api/central/budget/1
Authorization: Bearer {{token}}