### Create a new Central 1
POST localhost:8080/api/central
Content-Type: application/json

{
  "name": "Central Bruno",
  "email": "bruno.y.l.imai@gmail.com",
  "password": "central0000",
    "cellphone": "11999999999",
  "cnpj": "12348678902234"
}

### Create a new Central 2
POST localhost:8080/api/central
Content-Type: application/json

{
  "name": "aaaaaa",
  "email": "batata1@gmail.com",
  "password": "12345678",
  "cellphone": "11999999999",
  "cnpj": "12312678902234"
}

### Login como Central 1
POST localhost:8080/api/central/login
Content-Type: application/json

{
  "email": "bruno.y.l.imai@gmail.com",
  "password": "central0000"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.central.id)
%}


### Listar Todos os clientes da central
GET localhost:8080/api/central/client
Authorization: Bearer {{token}}

### Cadastra um Cliente
POST localhost:8080/api/central/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Bruno",
    "cpf": "12345678901",
    "address": "Rua dos bobos, n 0",
    "complement": "Sobrado 2",
    "cellphone": "11999999999",
    "email": "bruno.y.l.imai@gmail.com"
}

### Esqueci a senha central 1
POST localhost:8080/api/central/login/sendToken?email=bruno.y.l.imai@gmail.com

### Validar o token central 1
POST localhost:8080/api/central/login/validateToken?email=bruno.y.l.imai@gmail.com&code=320cce

### Alterar a senha
POST localhost:8080/api/central/login/resetPassword
Content-Type: application/json

{
    "password": "NovaSenha1234",
    "token": "320cce"
}

### Criar novo Worker
POST localhost:8080/api/central/worker
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cleiton",
    "email": "tesewee@gmail.com",
    "password": "12345678",
    "cellphone": "11999999999",
    "cpf": "12245678901",
    "address": "Rua dos bobos, n 0"
}

### Lista todos os Workers
GET localhost:8080/api/central/worker
Authorization: Bearer {{token}}

### Lista um Worker
GET localhost:8080/api/central/worker/52
Authorization: Bearer {{token}}

### Atualiza um Worker
PUT localhost:8080/api/central/worker/52
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cleiton",
    "email": "teste@gmail.com",
    "password": "12345678",
    "cellphone": "11999999999",
    "cpf": "12345678901",
    "address": "Rua dos bobos, n 0"
}

### Deleta um Worker
DELETE localhost:8080/api/central/worker/2
Authorization: Bearer {{token}}


### Lista o usuário 2
GET localhost:8080/api/central/client/1
Authorization: Bearer {{token}}

### lista todos os usuários
GET localhost:8080/api/central/client
Authorization: Bearer {{token}}

### Cria categoria
POST localhost:8080/api/central/category?name=Pato
Authorization: Bearer {{token}}

### Lista todas as categorias
GET localhost:8080/api/central/category
Authorization: Bearer {{token}}

### Atualiza categoria
PUT localhost:8080/api/central/category/1?name=Ar-Condicionado
Authorization: Bearer {{token}}

### Deleta categoria
DELETE localhost:8080/api/central/category/1
Authorization: Bearer {{token}}

### Cadastra serviço 1
POST localhost:8080/api/central/assistance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Concerto maquina de lavar",
  "name": "Concerto",
  "address": "R. Mal. Cardoso Júnior, 563 - Jardim das Américas, Curitiba - PR, 81530-420, Brazil",
  "cpf": "12345678901",
  "period": "Manha",
  "workersIds": [2]

}

### Cadastra serviço 2
POST localhost:8080/api/central/assistance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Concerto churrasqueira",
  "name": "Concerto",
  "address": "Av. Com. Franco, 4680 - Uberaba, Curitiba - PR, 81530-440, Brazil",
  "cpf": "12345678901",
  "period": "Manha",
  "workersIds": [2]
}

### Cadastra serviço 3
POST localhost:8080/api/central/assistance
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Concerto ar condicionado",
  "name": "Concerto",
  "address": "Av. Getúlio Vargas, 573 - Centro, Piraquara - PR, 83301-010, Brazil",
  "cpf": "12345678901",
  "period": "Manha",
  "workersIds": [1]
}
### Lista todos os serviços
GET localhost:8080/api/central/assistance
Authorization: Bearer {{token}}


### worker login
POST localhost:8080/api/worker/login
Content-Type: application/json

{
  "email": "teste@gmail.com",
  "password": "12345678"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.worker.id)
%}


### Lista servico mais proximo ao servico 1
GET localhost:8080/api/worker/assistance/closest?coordinate=-25.47156996804939, -49.228870016810575
Authorization: Bearer {{token}}


### Lista servico mais proximo ao servico 2
GET localhost:8080/api/worker/assistance/closest?coordinate=-25.450966074965084, -49.25218936712957
Authorization: Bearer {{token}}

### Lista servico mais proximo ao servico 3
GET localhost:8080/api/worker/assistance/closest?coordinate=-25.436354, -49.2693665
Authorization: Bearer {{token}}

### deleta servico 1
DELETE localhost:8080/api/central/assistance/52
Authorization: Bearer {{token}}

### cria um fornecedor
POST localhost:8080/api/central/supplierBusiness
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Novo Fornecedor 3",
  "cnpj": "99.887.766/5544-33"
}


### busca fornecedor
GET localhost:8080/api/central/supplierBusiness/53
Authorization: Bearer {{token}}

### busca fornecedor
GET localhost:8080/api/central/supplierBusiness/byCnpj/99.887.766%2F5544-33
Authorization: Bearer {{token}}


### lista fornecedores
GET localhost:8080/api/central/supplierBusiness
Authorization: Bearer {{token}}

### atualiza fornecedor
PUT localhost:8080/api/central/supplierBusiness/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Fornecedor Atualizado",
  "cnpj": "99887766554433"
}

### busca fornecedor pelo cnpj
GET localhost:8080/api/central/supplierBusiness/byCnpj?cnpj=12.345.678/F9101-24
Authorization: Bearer {{token}}

### deleta fornecedor
DELETE localhost:8080/api/central/supplierBusiness/1
Authorization: Bearer {{token}}

### lista produtos de um fornecedor
GET localhost:8080/api/central/supplierBusiness/2/products
Authorization: Bearer {{token}}

### cria um novo produto
POST localhost:8080/api/central/product
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Produto Novo",
  "price": 99.99,
  "supplierCnpj": 53
}

### lista produtos
GET localhost:8080/api/central/product
Authorization: Bearer {{token}}


### busca produto
GET localhost:8080/api/central/product/1
Authorization: Bearer {{token}}

### atualiza produto
PUT localhost:8080/api/central/product/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Produto Atualizado",
  "price": 9999999.99,
  "supplierId": 2
}

### deleta produto
DELETE localhost:8080/api/central/product/1
Authorization: Bearer {{token}}

### cria Client Business
POST localhost:8080/api/central/clientBusiness
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente Business",
  "cnpj": "12.345.678/F9101-24",
  "cellphone": "11999999999"
}

### lista Client Business
GET localhost:8080/api/central/clientBusiness
Authorization: Bearer {{token}}

### busca Client Business
GET localhost:8080/api/central/clientBusiness/1
Authorization: Bearer {{token}}

### atualiza Client Business
PUT localhost:8080/api/central/clientBusiness/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente Business Atualizado",
  "cnpj": "12.345.678/F9101-24",
  "cellphone": "11999999999"
}

### deleta Client Business
DELETE localhost:8080/api/central/clientBusiness/1
Authorization: Bearer {{token}}