### Create a new Central
POST localhost:8080/api/central
Content-Type: application/json

{
  "name": "Central 1",
  "email": "Central@gmail.com",
  "password": "central0000"
}

### Login como Central
POST localhost:8080/api/central/login
Content-Type: application/json

{
  "email": "Central@gmail.com",
  "password": "central0000"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.central.id)
%}


### Listar Todos os clientes da central
GET localhost:8080/api/central/client
Authorization: Bearer {{token}}

### Cadastra um Cliente
POST localhost:8080/api/central/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Bruno",
    "email": "bruno.y.l.imai@gmail.com",
    "password": "bruno1234",
    "cellphone": "11999999999",
    "address": "Rua dos bobos, n 0",
    "cpf": "12345678901"
}


### Lista o usuário 2
GET localhost:8080/api/central/client/2


### Exclui o usuário
DELETE localhost:8080/api/users/2
Authorization: Bearer {{token}}

### Exclui o evento 2
DELETE localhost:8080/api/users/events/2
Authorization: Bearer {{token}}

### Cria categoria
POST localhost:8080/api/events/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Rpg"
}

### Cria evento
POST localhost:8080/api/users/events
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Rpg",
  "local": "Minha casa",
  "hour": "12:00",
  "description": "Traga os dados",
  "creatorId": 102,
  "categoryId": 56
}